### ISSUE TITLE
Getting `Error: Groups are not supported` when not using groups

### ISSUE THREAD

**Issue by bruc3yan** [mafintosh/protocol-buffers#38]
Hello, 

I'm trying to get both encode (currently working!) and decode (not working) to work with the latest version of protocol-buffers; however, every time I try to call `.decode`, I get the following in my shell:

```shell
% node example.js
encoded vehicle <Buffer 00 c0 a9 07 02 08 43 61 64 69 6c 6c 61 63>
/Users/test/test/node_modules/protocol-buffers/compile.js:21
    throw new Error('Groups are not supported')
          ^
Error: Groups are not supported
    at skip (/Users/test/test/node_modules/protocol-buffers/compile.js:21:11)
    at Object.decode (eval at <anonymous> (/Users/test/test/node_modules/protocol-buffers/node_modules/generate-function/index.js:55:21), <anonymous>:30:16)
    at Object.<anonymous> (/Users/test/test/pf.js:24:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Here's my `example.js` file:
```javascript
var protobuf = require('protocol-buffers/require');
var schema = protobuf('schema.proto');

var vehicle = {
  price: 120000,
  make: 'Cadillac'
};

var encodeObj = schema.Vehicle.encode(vehicle);
console.log('encoded vehicle', encodeObj);

var decodeObj = schema.Vehicle.decode(encodeObj);
// console.log('decoded vehicle', decodeObj);
```
I don't believe that I have nesting or groups in my simple code but I still can't figure out why it's showing the error.
Here's my `package.json` file
```json
{
    "name":"test",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "start": "nodemon ./example.js"
    },
    "dependencies": {
        "express": "*",
        "mongodb": "*",
        "mongoose": "*",
        "kafka-node": "*",
        "protocol-buffers": "*",
        "nodemon": "*",
        "resolve-protobuf-schema": "*"
    }
}
```
And here's my `schema.proto` file:
```proto
message Vehicle {
  optional int32 price = 0;
  required string make = null;
}
```

**Comment by bruc3yan** [comment]
Actually, this is interesting.  It seems it's not really a group issue but more of a user error.  If I change null to an integer, the app runs fine.

New `schema.proto` file:
```protocol-buffers
message Vehicle {
  optional int32 price = 0;
  required string make = 2;
}
```

Here's the correct console output:
```shell
% node example.js
encoded vehicle <Buffer 00 c0 a9 07 0a 08 43 61 64 69 6c 6c 61 63>
decoded vehicle { price: 120000, make: 'Cadillac' }
```

I'm not sure where I got the `null` from, but Google Protocol buffer docs states `2` should be good.  [Protocol Buffer Documentation](https://developers.google.com/protocol-buffers/docs/encoding#structure)

**Comment by mafintosh** [comment]
Yea you're right. I don't know if there is a way to better tell the user what is wrong
