### ISSUE TITLE
TypeError: Object <Buffer ...> has no method 'readFloatLE'

### ISSUE THREAD

**Issue by chuntley** [mafintosh/protocol-buffers#8]
Hello, I am using PostMan to post a binary string generated from your example, and am getting the following error: 

```javascript
TypeError: Object <Buffer 0d 00 00 28 42 12 0b 68 65 6c 6c 6f 20 77 6f 72 6c 64> has no method 'readFloatLE'
    at Object.exports.float.decode (C:\path\node_modules\protocol-buffers\encodings.js:233:22)
    at Object.decode (eval at <anonymous> (C:\path\node_modules\protocol-buffers\node_modules\generate-function\index.js:88:21), <anonymous>:20:24)
```

I've simplified the code as much as I can, here is what I have so far (using Express):

```javascript
app.use (function(req, res, next) {
    var data='';

    req.on('data', function(chunk) {
        data += chunk;
    });

    req.on('end', function() {
        req.body = data;
        next();
    });
});

app.post('/', function(req, res)
{
    var fs = require('fs');
    var protobuf = require('protocol-buffers');

    var test = req.body;
    var messages = protobuf(fs.readFileSync('sample.proto'))
    var obj = messages.Test.decode(test);
    console.log(obj); 

    res.end();
});
```

As you can see, I'm trying to get the protocol buffer from a post request and decoding it so I can use it in my node application.

I have also tried taking the post request and converting it to a base64 string:

```javascript
test = new Buffer(req.body).toString('base64');
```

And this gives a different error:

```javascript
Error: Groups are not supported
    at skip (C:\path\node_modules\protocol-buffers\compile.js:21:11)
    at Object.decode (eval at <anonymous> (C:\path\node_modules\protocol-buffers\node_modules\generate-function\index.js:88:21), <anonymous>:30:16)
```

Thank you for taking a look at this!

**Comment by mafintosh** [comment]
if this is still an issue feel free to reopen
